### ISSUE TITLE
Dropdown empty

### ISSUE THREAD

**Issue by strarsis** [qstudio/filter-media-library-by-post#1]
@qstudio: The dropdown is completely empty and lists no posts to filter for.
That's because the plugin currently has the post types to use hardcoded (`property`).
A setting or at least a filter should be offered that allows to change the post types to query for.

**Comment by maketheboat** [comment]
@strarsis - thanks for your feedback - 6 years since we've even looked at this repo - to be honest, I did not know it existed!

If you have a use for this plugin and can see how to fix it, I'd suggest you fork and make a PR - good luck!

**Comment by maketheboat** [comment]
You are right, a simple filter could be added when the $post_type property is used:

For example:

`self::$post_type = \apply_filters( q/filter_media_library_by_post/post_type, self::$post_type );`

**Comment by strarsis** [comment]
@qstudio: I find your plugin very useful, I wasn't able to find any other plugin that offers this functionality, 
which baffles me, as this should be something that is needed quite often...

**Comment by maketheboat** [comment]
I'll push a quick fix up for you to try - give me 10.

**Comment by strarsis** [comment]
@qstudio: Any if your got some more time, please publish this to the official WordPress plugin repository. :)

**Comment by maketheboat** [comment]
I'll let you try it here first - you can manage plugins via github nicely with the github updater plugin.

I guess it'll take me a bit longer to fix this up, as I'll do some proper testing and reading about existing options also.

you'll get a notification when it's up.

**Comment by strarsis** [comment]
@qstudio: Please also add a composer.json so this plugin can be installed using composer. Composer is often used, as with roots.io Bedrock sites.

**Comment by maketheboat** [comment]
You can try 0.0.2 - it might be a bit slow as it required a few custom wpdb queries to work correctly.

Please feel free to fork and add your own requirements, such as Composer config files - we don't use them or Roots.

**Comment by strarsis** [comment]
@qstudio: Thanks, just tried the new release.
So the list now contains page posts. But some post types still seem to be missing, like the WooCommerce `product` post types.

**Comment by maketheboat** [comment]
Yep - only post + page post_types are fetched, but the following filter can be used to extend those:

`\add_filter( 'q/filter_media_library_by_post/post_type', function(){ return [ 'post', 'custom_post_type' ]; });`

**Comment by strarsis** [comment]
Thanks, this works great:
```php
add_filter( 'q/filter_media_library_by_post/post_type', function( $post_types ) {
  return array_merge( $post_types, [ 'product' ] );
} );
````

**Comment by strarsis** [comment]
@qstudio: If you are interested, you can take a look at this PR: https://github.com/qstudio/filter-media-library-by-post/pull/2
It adds composer support. As license GPL-v2 or later is used (as the README says).
Ideally you could add a LICENSE(.md) for GPL-v2 so GitHub can recognize the license for this repository automatically.

**Comment by strarsis** [comment]
@qstudio: Edit: The actual reason for the empty result list was that those media posts were in trash (Media library trash is enabled on that site), but view was set to default (not trash). Your plugin queries fine.

**Comment by maketheboat** [comment]
The plugin could do with some extra sanity checks to ensure that filtered values are an array and perhaps to check that requested post_types exist - but I imagine the performance will already be a bit slow - the issue is that we need to alter the global wp_query and this impacts all other queries run on the page load - hence the need to built sql directly to get data.
